backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pagina's"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Subtitel", name: "subtitle", widget: "text" }
          - { label: "Hero afbeelding", name: "heroImage", widget: "image" }
